version: "3.9"

services:
  # Banco de Dados
  postgres:
    image: postgres:16
    container_name: paggo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: paggo
      POSTGRES_PASSWORD: paggo
      POSTGRES_DB: paggo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # IA Local (Ollama)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  postgres_data:
  ollama_data: